baseURL: "https://touno.io/"
languageCode: "en-us"
title: "TOUNO.io"
theme: "ghostwriter"
copyright: Kananek T.
googleAnalytics: UA-70130307-8

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: Kananek T.
  profile: "https://mr.touno.io"

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: Kananek T. 🌑
  description: 🤣 Write whatever I write it down. 
  github: "https://github.com/dvgamerr"
  twitter: "https://twitter.com/dvgamerr"
  facebook: "https://www.facebook.com/dvgamerr"
  shareTwitter: true
  rss: true
  shareFacebook: true
  shareLinkedIn: false
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""
  # If you want to use plausible(https://plausible.io) for analytics, add this section
  plausibleAnalytics:
    domain: ""
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL: ""

permalinks:
  post: "/:year/:month/:day/:filename/"
